# Generated by Django 3.2.25 on 2024-03-18 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bookNumberTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookId', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='bookStallBooksTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(max_length=12)),
                ('name', models.CharField(max_length=12)),
                ('author', models.CharField(max_length=12)),
                ('language', models.CharField(max_length=12)),
                ('rate', models.FloatField()),
                ('stock', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='issueTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('returnDate', models.DateField()),
                ('status', models.CharField(max_length=100)),
                ('fineAmount', models.FloatField()),
                ('BOOKNUMBER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libraryapp.booknumbertable')),
            ],
        ),
        migrations.CreateModel(
            name='libraryTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=12)),
                ('place', models.CharField(max_length=12)),
                ('phone', models.BigIntegerField()),
                ('date', models.DateField()),
                ('email', models.CharField(max_length=24)),
                ('post', models.CharField(max_length=12)),
                ('pin', models.CharField(max_length=12)),
                ('photo', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='librayBookTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(max_length=24)),
                ('bookName', models.CharField(max_length=30)),
                ('author', models.CharField(max_length=24)),
                ('quantity', models.BigIntegerField()),
                ('language', models.CharField(max_length=24)),
                ('LIBRARY', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libraryapp.librarytable')),
            ],
        ),
        migrations.CreateModel(
            name='loginTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=24)),
                ('password', models.CharField(max_length=24)),
                ('type', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='userTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=12)),
                ('place', models.CharField(max_length=12)),
                ('post', models.CharField(max_length=12)),
                ('pin', models.CharField(max_length=10)),
                ('phone', models.BigIntegerField()),
                ('email', models.CharField(max_length=40)),
                ('photo', models.FileField(upload_to='')),
                ('LOGIN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libraryapp.logintable')),
            ],
        ),
        migrations.CreateModel(
            name='reviewTable2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.CharField(max_length=120)),
                ('rating', models.FloatField()),
                ('date', models.DateField()),
                ('BOOK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libraryapp.libraybooktable')),
                ('USER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libraryapp.usertable')),
            ],
        ),
        migrations.CreateModel(
            name='reviewTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.CharField(max_length=120)),
                ('rating', models.FloatField()),
                ('date', models.DateField()),
                ('BOOK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libraryapp.bookstallbookstable')),
                ('USER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libraryapp.usertable')),
            ],
        ),
        migrations.CreateModel(
            name='preBookingTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(max_length=100)),
                ('LIBRARYBOOK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libraryapp.libraybooktable')),
                ('USER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libraryapp.usertable')),
            ],
        ),
        migrations.CreateModel(
            name='paymentTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('date', models.DateField()),
                ('status', models.CharField(max_length=102)),
                ('ISSUE', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libraryapp.issuetable')),
            ],
        ),
        migrations.CreateModel(
            name='ordersTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(max_length=30)),
                ('USER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libraryapp.usertable')),
            ],
        ),
        migrations.CreateModel(
            name='orderItemsTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.CharField(max_length=100)),
                ('BOOKSTALLBOOKS', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libraryapp.bookstallbookstable')),
                ('ORDER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libraryapp.orderstable')),
            ],
        ),
        migrations.CreateModel(
            name='offersTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offers', models.CharField(max_length=100)),
                ('offerDetails', models.CharField(max_length=100)),
                ('offerPeriod', models.DateField()),
                ('BOOKSTALL', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libraryapp.bookstallbookstable')),
            ],
        ),
        migrations.AddField(
            model_name='librarytable',
            name='LOGIN',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libraryapp.logintable'),
        ),
        migrations.AddField(
            model_name='issuetable',
            name='LIBRARYBOOK',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libraryapp.libraybooktable'),
        ),
        migrations.AddField(
            model_name='issuetable',
            name='USER',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libraryapp.usertable'),
        ),
        migrations.CreateModel(
            name='feedbackTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.CharField(max_length=120)),
                ('date', models.DateField()),
                ('rating', models.FloatField()),
                ('LOGIN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libraryapp.logintable')),
                ('USER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libraryapp.usertable')),
            ],
        ),
        migrations.CreateModel(
            name='bookstallTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=12)),
                ('place', models.CharField(max_length=12)),
                ('ownerName', models.CharField(max_length=12)),
                ('phone', models.BigIntegerField()),
                ('date', models.DateField()),
                ('email', models.CharField(max_length=24)),
                ('post', models.CharField(max_length=24)),
                ('pin', models.CharField(max_length=10)),
                ('lattitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('photo', models.FileField(upload_to='')),
                ('LOGIN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libraryapp.logintable')),
            ],
        ),
        migrations.AddField(
            model_name='bookstallbookstable',
            name='BOOKSTALL',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libraryapp.bookstalltable'),
        ),
        migrations.AddField(
            model_name='booknumbertable',
            name='LIBRARY_BOOK',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libraryapp.libraybooktable'),
        ),
    ]
