# Generated by Django 3.2.25 on 2024-03-18 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookstalltable',
            name='lic',
            field=models.CharField(default='hello', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='librarytable',
            name='lic',
            field=models.CharField(default='hello', max_length=100),
            preserve_default=False,
        ),
    ]
