# Generated by Django 3.2.21 on 2024-02-14 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookstallbookstable',
            name='language',
            field=models.CharField(default='malayalam', max_length=12),
            preserve_default=False,
        ),
    ]
