# Generated by Django 3.2.21 on 2024-02-28 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0002_bookstallbookstable_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderstable',
            name='total',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
