# Generated by Django 3.2.25 on 2024-03-15 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0008_auto_20240315_2303'),
    ]

    operations = [
        migrations.DeleteModel(
            name='reviewTable2',
        ),
    ]
